version: "3.9"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: repomultilingua_agt
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
